framework:
    cache:
        # Уникальное имя приложения для стабильных пространств имен
        prefix_seed: your_app_name

        # Основной адаптер Redis
        app: cache.adapter.redis
        default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/0'

        pools:
            # Основной пул приложения с поддержкой тегов
            # ВАЖНО: не используйте зарезервированные имена cache.app, cache.system
            app.cache:
                adapter: cache.adapter.redis
                provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/0'
                tags: true
                default_lifetime: 3600

            # Пул для сессий
            app.sessions:
                adapter: cache.adapter.redis
                provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/1'

            # Пул для долгоживущих данных
            app.long_term:
                adapter: cache.adapter.redis
                provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/2'
                tags: true
                default_lifetime: 86400 # 24 часа