monolog:
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug

    elklogger:
       type: service
       id: Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler
       channels: ["!event"]
       lazy: true
