parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Алиас для основного кэша с тегами
    # Используем наш кастомный пул вместо зарезервированного cache.app
    Symfony\Contracts\Cache\TagAwareCacheInterface:
        alias: app.cache

    # Дополнительные алиасы
    app.long_term_cache:
        alias: app.long_term

    # Elasticsearch handler
    Symfony\Bridge\Monolog\Handler\ElasticsearchLogstashHandler:
        arguments:
            $endpoint: '%env(ELASTICSEARCH_HOST)%'
            $index: "symfony-logs"
            $client: null
            $bubble: true